# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungequation',
            name='error',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lungequation',
            name='iterations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lungequation',
            name='learning_rate',
            field=models.FloatField(null=True),
        ),
    ]
