# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_function', '0002_auto_20180426_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField()),
                ('trained', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FEV1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField()),
                ('trained', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FVC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField()),
                ('trained', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PEF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField()),
                ('trained', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
